language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: tutorial-cicd
  api_key:
    secure: uut4WC+iQ402jlxLbBtRC0+uGqC0c9z3GnwLJ/qlaPtizB0cx5q+oddh22iCjxc4KkL1V5HZvEKOdJqA+F9yScK/FF8yqY5Z+N2XlNjJu+kxxSqSPVGhmaZ3D8EJElAg78PMw0NuRBo1lX7VKuMMTVdTF181Z6f/xqAhtAcIy7bllE8GZjqbB+fdVoIvUAvvrLMCcPb4WpF7UceRvdLeU9+RDN/8ENH12eUeL+9T8Eq3KHTUF7K6rGtIVSaKXLIFGrOicxLDZNYVa4j/mVW3VOe2Oc7p6oCMbs51o290hjZJ8kVU6TRP43xxrfCuzISlFCz7BtqczsIaGQ5YvsjknaxoWJfx0z6Q5XO3y4ariiRQwdosNagta95ZtYCt4pI7M+OQi/Vp6oAtM0xVk3tLWm08b/stngAOlZUYXkz54ewfemqjyFdmP7nC0nGxbuRczE56gHt5tbr04avb1OPw3mDOpdJmB3YLc4ZFist7Ll+Cccgpwtg8VLgkSDW6oGKZgwg6pNSBZHYUIC/YKaL3IR+1lYFpermNjBR0JMD8Aq9JaryM66Hnxs550KiYYM28ZXFTxZGBd7dsClb9n9+jNkBo+sNTkWz8Z2nctlKt5uPDtx+zJl33OIymdFF15kYSShLjHATb53wD0ksaEw6P08pzYJMEZKVh5h2FxMwIV4A=
