language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: tutorial-cicd
  api_key:
    secure: qzr/oNSt+SbChg1bCZ4usV39G1M8u5jeehJGlvIkuzUMkObntIQ+KBxWzUDKFvJFigi+pt+FyWO/qfrjKsD7vqpJLaA0OtYXRLTGlQQLZC2RmV2tIo95hJP5ew7MSM7qABQEI1Ih6fwGBoA7DpjkCihG8VrETy4TunbX61OjnQFoTou+Gy2sJ9eFLg84bXQV/nSC+sotaplOmrGNBDMsYfwWviDJgAeZlB/vIx5gdG07fr+N1GTi2uuiSV5df01uB5UpTOSy+ZcNcdl7rUclHKNXHK8pnfSpVQJvB0sGgnLeAeuU3EfwNNlQIN6OdltugWccz06iH5w8Lk10U0rmrj5roA+btmZ987E3GhR8kQ+v3qIk5obHv4kag1cmrIaaPztA0UzGnfnyC2qXWXv+9eGc8Erf9OTrQ24dSAXKPScxZ/uLn9uJTSL+AFh4UgvA+lSpBEV14NOplL4QEhd5v3tWV3xs71VOqueMMpK5aUkgw9Gt2xDu7WJb/r27/H5BFke8wO3gAymW840WI8wWikHyybIjEAG+ElR5TyT6qdr3xUcAnvtrO7HFc7GIv6ny8vywDPv3I4blsDN1lcsLkETDwtcZWQowLJr9ChRLu7qEiFIGYJsdtTlW6MlN5xrxa46e606rMKSiYwBMfyIE8qQeHpH0eDY9XyDNV0hVmec=
